import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MusicAI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-tr from-[#fff_8%] via-[#BAE6FD_40%] to-[#fff_90%] bg-no-repeat bg-[300%,300%] animate-wave'>
        {children}
        </body>
    </html>
  )
}

// inter.className}- was in the body className